#!/bin/sh
#
# /etc/init.d/xrd-rep-snatcher - Start/stop the xrd-rep-snatcher service
#
# The following two lines allow this script to be managed by Fedora's
# chkconfig program.
#
# chkconfig: - 80 30
# description: xrd-rep-snatcher collects monitoring data from xrootd and cmsd processes.

# Source function library.
SYSTEMCTL_SKIP_REDIRECT=please
. /etc/rc.d/init.d/functions

if [ -e /etc/sysconfig/xrootd ]; then
    . /etc/sysconfig/xrootd
else
    XROOTD_USER=root
fi

prog=xrd-rep-snatcher.pl
pidfile=${PIDFILE-/var/run/xrootd/xrd-rep-snatcher.pid}
lockfile=${LOCKFILE-/var/lock/subsys/xrd-rep-snatcher}

start() {
    echo -n "Starting xrd-rep-snatcher: "
    daemon --user $XROOTD_USER --pidfile ${pidfile} ${prog}
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch ${lockfile}
    return $RETVAL
}

# A function to stop a program.
stop() {
    echo -n "Shutting down xrd-rep-snatcher: "
    killproc -p ${pidfile} ${prog}
    RETVAL=$?
    echo
    rm -f ${lockfile}
    return $RETVAL
}

restart() {
    stop
    start
    return $RETVAL
}

reload() {
    echo -n "Reloading configuration of xrd-rep-snatcher: "
    if [ ! -f ${pidfile} ]; then
     	echo_failure;
	echo
	echo "  There is no pidfile ..."
     	return 1;
    fi
    pid=`cat ${pidfile}`
    kill -1 ${pid} && echo_success && return 0
    echo_failure && return 1
}

case $1 in 
'start')
    start
    ;;
'stop')
    stop
    ;;
'status')
    status -p ${pidfile} ${prog}
    ;;
'reload')
    reload
    ;;
'restart')
    restart
    ;;
'condrestart')
    [ -f ${lockfile} ] && restart
    ;;
*)
    echo "usage: $0 {start|stop|status|restart|condrestart}"
    ;;
esac

exit $?
